#!/bin/bash
# This script is executed every time your instance is spawned.

# Clone the pwnbox repo and get user_init up to date
cd
cd my_data
rm -rf pwnbox
git clone https://github.com/HiperonLambda/pwnbox
cp ./pwnbox/user_init ./user_init # Ensure we have the latest version of user_init

# Append pwnbox .bashrc to .bashrc if it's not already there
if ! grep -q "pwnbox" ~/.bashrc; then
  echo "" >> ~/.bashrc
  echo "# pwnbox additions to .bashrc" >> ~/.bashrc
  echo "source ~/my_data/pwnbox/.bashrc" >> ~/.bashrc
fi

# Make pwnbox scripts executable
for file in ~/my_data/pwnbox/scripts/*;
do
  if [[ -f $file ]]; then
    chmod +x $file
  fi
done

# Make pwnbox memos executable
for file in ~/my_data/pwnbox/memos/*;
do
  if [[ -f $file ]]; then
    chmod +x $file
  fi
done

# fzf on ParrotOS is stale, so we need to install it from source
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
echo "y" | ~/.fzf/install

# Set up gnome-keyring-daemon so we don't get prompted to set a password during apt installations
echo -n "htb-tkit" | gnome-keyring-daemon --unlock

# Set default file types to be opened by VS Code (codium) by default
xdg-mime default codium.desktop application/octet-stream # files with no extension
xdg-mime default codium.desktop text/plain
xdg-mime default codium.desktop application/x-shellscript
xdg-mime default codium.desktop text/x-csharp
xdg-mime default codium.desktop text/x-c
xdg-mime default codium.desktop text/x-python
xdg-mime default codium.desktop application/javascript
xdg-mime default codium.desktop text/typescript
xdg-mime default codium.desktop text/html
xdg-mime default codium.desktop text/css
xdg-mime default codium.desktop application/x-ruby
xdg-mime default codium.desktop application/x-perl
xdg-mime default codium.desktop application/x-php

sudo apt update &